set -g default-terminal screen-256color
set -g mode-keys vi
set -g mouse on
set -g base-index 1

# rebind prefix to ctrl+a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# ctrl+a r to reload config
bind r source-file ~/.tmux.conf

# nicer navigation between panes
bind -n M-Left  select-pane -L
bind -n M-h     select-pane -L
bind -n M-Right select-pane -R
bind -n M-l     select-pane -R
bind -n M-Up    select-pane -U
bind -n M-k     select-pane -U
bind -n M-Down  select-pane -D
bind -n M-j     select-pane -D

# look and feel
set -g status-style ""
set -g status-position top
set -g status-left-length 100
set -g status-left "#[bold]#S #[nobold]|"
set -g window-status-current-format " #[bold,underscore]#I:#W"
set -g window-status-format " #I:#W"
set -g message-style ""
