set -g default-terminal screen-256color

set -g mouse on

set -g focus-events on

set -g base-index 1
setw -g pane-base-index 1

set -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-clipboard"

# rebind prefix to ctrl+a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# ctrl+a r to reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded config."

# vim-style pane navigation
bind -n M-Left  select-pane -L
bind -n M-h     select-pane -L
bind -n M-Right select-pane -R
bind -n M-l     select-pane -R
bind -n M-Up    select-pane -U
bind -n M-k     select-pane -U
bind -n M-Down  select-pane -D
bind -n M-j     select-pane -D

# vim-style pane resizing
bind -n M-S-Left  resize-pane -L 5
bind -n M-H       resize-pane -L 5
bind -n M-S-Right resize-pane -R 5
bind -n M-L       resize-pane -R 5
bind -n M-S-Up    resize-pane -U 5
bind -n M-K       resize-pane -U 5
bind -n M-S-Down  resize-pane -D 5
bind -n M-J       resize-pane -D 5

# look and feel
set -g status-style ""
set -g status-position top
set -g status-left ""
set -g status-right "#[bold]#S"
set -g window-status-current-format " #[bold,underscore]#I:#W"
set -g window-status-format " #I:#W"
set -g message-style ""

