#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:text'

    [blocks.segments.properties]
      style = 'full'
      template = '{{ .Path }}'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{ if gt .Code 0 }}p:red{{ end }}',
      '{{ if eq .Code 0 }}p:text{{ else }}',
    ]
    template = '❯'

[[blocks]]
  type = 'rprompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = 'p:text'

  [[blocks.segments]]
    type = 'os'
    style = 'plain'


[transient_prompt]
  foreground_templates = [
    '{{ if gt .Code 0 }}p:red{{ end }}',
    '{{ if eq .Code 0 }}p:text{{ else }}',
  ]
  newline = false
  template = '❯ '

[palette]
  text = '#cad3f5'
  sapphire = '#7dc4e4'
  red = '#ed8796'
  green = '#a6da95'
