# lenowo
["Chimei Innolux Corporation - 0x14E5 - eDP-1"]
path = "/home/red/.local/share/wallpapers/solar-system-minimal.png"

# x390
["California Institute of Technology - 0x130F - eDP-1"]
path = "/home/red/.local/share/wallpapers/solar-system-minimal.png"
